### ISSUE TITLE
Wiki Page, Schema, Backend Routes, MVP List

### ISSUE THREAD

**Issue by TahjDev** [omarluq/ExpectoStayLonger#1]
## MVP List
- Could you also add a bit more info under MVP's about what a user can do with said listing what they can see or if others users can or cannot see said MVP
- Your `Production ReadMe` should be MVP number 7 as it is the last thing you will write because it will hold implementation details and such
- Can users edit a reservation?
- Will you be covering the functionality around a slot already being taken
- Will there be a Map showing said listing?
- What things will they be able to filter by
- Are you going to have a set number of things to filter by, ie: will a user only be able to filter by a select number of cities

## Schema
- Could you add a bit of info under your tables just about things you are indexing and why. It doesnt have to be obvious ones like id. The same goes for unique constraints that aren't obvious as well

## Backend Routes
- Correct me if im wrong but I don't think you can delete or update reviews on Airbnb. If you cant then you wont need those routes
- You dont need a show page for the users reservation. You could just use the assocation from  a user. `@user.reservations`
- Same things for reviews on a listing `@reviews.lstings`

**Comment by omarluq** [comment]
MVP List
Can users edit a reservation? no a user can usually make a reservation and cancel it on airbnb 
Will you be covering the functionality around a slot already being taken
Will there be a Map showing said listing? i listed this under the search for listings 
What things will they be able to filter by
Are you going to have a set number of things to filter by, ie: will a user only be able to filter by a select number of cities? yes i was thinking of only implementing city and dates search for starts and maybe implement filters later if the project comes along nicely within time!

**Comment by omarluq** [comment]
Schema
Could you add a bit of info under your tables just about things you are indexing and why. It doesnt have to be obvious ones like id. The same goes for unique constraints that aren't obvious as well? I have left the indexing info and the unique flag in the details

**Comment by TahjDev** [comment]
Will there be a Map showing said listing? i listed this under the search for listings. -----On airbnb when you go to a listings show page there is a map showing said listing and their location on a map on that page, is that the one you meant?

Could you add a bit of info under your tables just about things you are indexing and why. It doesnt have to be obvious ones like id. The same goes for unique constraints that aren't obvious as well? I have left the indexing info and the unique flag in the details.-------You need info under the table as well about the details and what foregin keys are referencing, reference the sipper docs for more info.

**Comment by omarluq** [comment]
Will there be a Map showing said listing? i listed this under the search for listings. -----On airbnb when you go to a listings show page there is a map showing said listing and their location on a map on that page, is that the one you meant? yes


Could you add a bit of info under your tables just about things you are indexing and why. It doesnt have to be obvious ones like id. The same goes for unique constraints that aren't obvious as well? I have left the indexing info and the unique flag in the details.-------You need info under the table as well about the details and what foregin keys are referencing, reference the sipper docs for more info. do i need to do it for foregin keys only? or do i have to do it for the user table?

**Comment by omarluq** [comment]
Backend Routes
Correct me if im wrong but I don't think you can delete or update reviews on Airbnb. If you cant then you wont need those routes
You dont need a show page for the users reservation. You could just use the assocation from a user. @user.reservations
Same things for reviews on a listing @reviews.lstings 


completed all the above

**Comment by omarluq** [comment]
everything has been completed
